name: Publish crates

on:
  release:
    types: [released, prereleased]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: [plutus-parser-derive, plutus-parser]
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - name: Publish ${{ matrix.package-name }} to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p ${{ matrix.package-name }}
